
num of classes:  1701
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
  0%|                                                                                                                           | 0/800 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/mohammed/Workspace/csci499-project/code/MMBERT/vqamed2019/train.py", line 168, in <module>
    train_loss, _, _, _, _ = train_one_epoch(trainloader, model, optimizer, criterion, device, scaler, args, idx2ans)
  File "/Users/mohammed/Workspace/csci499-project/code/MMBERT/vqamed2019/utils.py", line 557, in train_one_epoch
    logits, _, _ = model(img, question_token, segment_ids, attention_mask)
  File "/Users/mohammed/Workspace/csci499-project/code/MMBERT/vqamed/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/Users/mohammed/Workspace/csci499-project/code/MMBERT/vqamed2019/utils.py", line 529, in forward
    h, attn_scores, intermediate = self.transformer(img, input_ids, segment_ids, input_mask)
  File "/Users/mohammed/Workspace/csci499-project/code/MMBERT/vqamed/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/mohammed/Workspace/csci499-project/code/MMBERT/vqamed2019/utils.py", line 505, in forward
    h[i][1] = v_2[i]
RuntimeError: The expanded size of the tensor (768) must match the existing size (312) at non-singleton dimension 0.  Target sizes: [768].  Tensor sizes: [312]